name: ppo
class_string: stable_baselines3:PPO
algo_cfg:

env_wrappers:
- class_string:
  wrapper_args:
  vec_class_string: stable_baselines3.common.vec_env:VecFrameStack
  vec_wrapper_args:
    n_stack: 4
    channels_order: null