config_name: default_training

# This will use the <algo> algorithm to train on the <env> environment 
# following the <training> training configuration. 
defaults:
  - algo: ppo
  - training: default_training
  - env: cartpole